[package]
name = "tinymvt"
version = "0.0.4"
edition = "2021"
license = "MIT"
description = "Simple library for serializing Mapbox Vector Tile (MVT) with minimal dependencies."

[dependencies]
foldhash = "0.1.4"
indexmap = "2.7.1"
prost = "0.13.5"

[build-dependencies]
prost-build = "0.13.5"
